---
- name: Set vCenter credentials
  ansible.builtin.set_fact:
    vcenter_credentials: &vcenter_credentials
      validate_certs: false
      hostname: "{{ vcenter_installation_ip }}"
      username: "{{ vcenter_installation_username }}"
      password: "{{ vcenter_installation_password }}"

- name: Add ESX servers
  community.vmware.vmware_host:
    <<: *vcenter_credentials
    datacenter_name: "{{ vcenter_installation_datacenter_name }}"
    cluster_name: "{{ vcenter_installation_cluster_name }}"
    esxi_hostname: "{{ inventory_hostname }}"
    esxi_username: "{{ ansible_user }}"
    esxi_password: "{{ ansible_password }}"
    state: present
  delegate_to: localhost

- name: Gather datastore facts
  community.vmware.vmware_datastore_info:
    <<: *vcenter_credentials
    datacenter_name: "{{ vcenter_installation_datacenter_name }}"
    gather_nfs_mount_info: false
    gather_vmfs_mount_info: false
  register: datastore_facts
  delegate_to: localhost

- name: Rename local datastore
  community.vmware.vmware_object_rename:
    <<: *vcenter_credentials
    object_name: "{{ item.name }}"
    new_name: "{{ inventory_hostname_short | upper }}_OS"
    object_type: 'Datastore'
  delegate_to: localhost
  with_items: "{{ datastore_facts.datastores }}"
  when: item.type == "VMFS" and item.name | regex_search('^datastore')
